# Site settings
title: "James Gotsell - the life and times of a Full Stack DEV"
description: "Writing is hard!."
baseurl: ""
url: "http://jamesgotsell.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "abt"
    url: /about
  - title: "twt"
    url: http://twitter.com/James_Gotsell
  - title: "git"
    url: http://github.com/JamesGotsell
  - title: "rss"
    url: /feed.xml
